namespace KeepClip.Infrastructure;

// Komunikaty widoczne dla użytkownika, które powstają poza przeglądarką: powiadomienia
// pulpitu, menu w zasobniku oraz treści błędów odsyłane przez API. Interfejs ma własne
// tłumaczenia w `frontend/i18n.js`; tutaj są wyłącznie teksty, których nie da się tam
// przenieść, bo powstają bez udziału otwartego okna.
internal static class Strings
{
    public static string Get(string key, params object?[] args)
    {
        var lang = Settings.GetLanguage();
        var text = Lookup(lang, key) ?? Lookup(Config.DefaultLanguage, key) ?? key;
        return args.Length == 0 ? text : string.Format(text, args);
    }

    private static string? Lookup(string lang, string key) =>
        Table.TryGetValue(lang, out var dict) && dict.TryGetValue(key, out var value) ? value : null;

    private static readonly Dictionary<string, Dictionary<string, string>> Table = new()
    {
        ["pl"] = new()
        {
            ["clip.notFound"]          = "Klip nie istnieje.",
            ["clip.fileMissing"]       = "Plik nie istnieje na dysku.",
            ["clip.playbackNotReady"]  = "Podgląd klipu nie jest jeszcze gotowy.",
            ["folder.nameRequired"]    = "Nazwa folderu jest wymagana.",
            ["folder.notFound"]        = "Folder nie istnieje.",
            ["segment.notFound"]       = "Segment nie istnieje.",
            ["search.queryRequired"]   = "Wpisz szukane słowa.",
            ["cloud.missingClientFile"] = "Brak pliku google_client.json w folderze data.",
            ["cloud.missingClientId"]  = "Brak client_id w pliku google_client.json.",
            ["update.noInstaller"]     = "Najnowsze wydanie nie zawiera pliku instalatora.",
            ["replay.ffmpegMissing"]   = "Brak ffmpeg.exe w tools\bin — uruchom setup.ps1.",
            ["audio.noEndpoint"]       = "Nie znaleziono urządzenia dźwiękowego do nagrywania.",
            ["cloud.notConnected"]     = "Nie połączono z Google Drive.",
            ["cloud.expired"]          = "Wygasło połączenie z Google Drive — połącz ponownie.",
            ["cloud.noTargetPath"]     = "Brak ścieżki docelowej klipu.",
            ["cloud.noRemoteId"]       = "Klip nie ma identyfikatora w chmurze.",
            ["config.transcribeBusy"]  = "Nie można zmieniać folderu w trakcie transkrypcji.",
            ["config.pathRequired"]    = "Ścieżka folderu jest wymagana.",
            ["config.pathMissing"]     = "Folder nie istnieje: {0}",
            ["config.notAFolder"]      = "To nie jest folder: {0}",
            ["config.badTheme"]        = "Nieobsługiwany motyw kolorystyczny.",
            ["config.badLanguage"]     = "Nieobsługiwany język.",
            ["folder.nameTooLong"]     = "Nazwa folderu za długa (maksymalnie 100 znaków).",
            ["folder.duplicate"]       = "Folder o nazwie „{0}” już istnieje.",
            ["media.pathMissing"]      = "Ścieżka nie istnieje.",
            ["media.explorerFailed"]   = "Nie udało się otworzyć Eksploratora: {0}",
            ["segment.textEmpty"]      = "Tekst nie może być pusty.",
            ["update.inProgress"]      = "Aktualizacja już trwa.",
            ["replay.badDuration"]     = "Długość powtórki musi mieścić się w zakresie 15–600 sekund.",
            ["replay.badFps"]          = "Obsługiwane wartości FPS: 30, 60 lub 90.",
            ["replay.badQuality"]      = "Nieobsługiwana jakość nagrania.",
            ["replay.badHotkey"]       = "Nieprawidłowy skrót — użyj modyfikatora i klawisza, np. Alt+F10.",
            ["replay.notRunning"]      = "Bufor powtórki nie jest uruchomiony.",
            ["replay.saveInProgress"]  = "Poprzedni zapis powtórki jeszcze trwa.",
            ["replay.bufferEmpty"]     = "Bufor powtórki jest jeszcze pusty — daj mu kilka sekund.",
            ["replay.muxFailed"]       = "Nie udało się złożyć powtórki (ffmpeg: {0})",
            ["replay.ffmpegStart"]     = "Nie udało się uruchomić ffmpeg.",
            ["replay.savingTitle"]     = "Zapisywanie powtórki…",
            ["replay.savingSubtitle"]  = "przetwarzanie, chwila…",
            ["replay.savedTitle"]      = "Powtórka zapisana",
            ["replay.saveFailedTitle"] = "Nie udało się zapisać powtórki",
            ["tray.open"]              = "Otwórz KeepClip",
            ["tray.exit"]              = "Zakończ i zatrzymaj nagrywanie",
            ["tray.tooltip"]           = "KeepClip — nagrywanie w tle",
            ["credential.tooLong"]     = "Sekret jest zbyt długi dla Menedżera poświadczeń.",
            ["drive.badPhotoUrl"]      = "Nieprawidłowy adres zdjęcia profilowego Google.",
            ["drive.photoTooLarge"]    = "Zdjęcie profilowe Google jest zbyt duże.",
            ["drive.badPhoto"]         = "Google nie zwrócił prawidłowego zdjęcia profilowego.",
            ["drive.badPhotoSize"]     = "Nieprawidłowy rozmiar zdjęcia profilowego Google.",
            ["drive.noUploadUrl"]      = "Dysk Google nie zwrócił adresu sesji wysyłania.",
            ["drive.noRefreshToken"]   = "Google nie zwrócił tokenu odświeżania.",
            ["transcribe.decodeFailed"] = "Nie udało się zdekodować audio: {0}",
            ["transcribe.noModel"]     = "Nie udało się uruchomić żadnego modelu transkrypcji.",
            ["trash.moveFailed"]       = "Nie udało się przenieść do Kosza (kod {0}).",
        },
        ["en"] = new()
        {
            ["clip.notFound"]          = "The clip does not exist.",
            ["clip.fileMissing"]       = "The file no longer exists on disk.",
            ["clip.playbackNotReady"]  = "The playback preview is not ready yet.",
            ["folder.nameRequired"]    = "A folder name is required.",
            ["folder.notFound"]        = "The folder does not exist.",
            ["segment.notFound"]       = "The segment does not exist.",
            ["search.queryRequired"]   = "Enter the words to search for.",
            ["cloud.missingClientFile"] = "The file google_client.json is missing from the data folder.",
            ["cloud.missingClientId"]  = "client_id is missing from google_client.json.",
            ["update.noInstaller"]     = "The latest release contains no installer file.",
            ["replay.ffmpegMissing"]   = "ffmpeg.exe is missing from tools\bin - run setup.ps1.",
            ["audio.noEndpoint"]       = "No audio device available for recording.",
            ["cloud.notConnected"]     = "Not connected to Google Drive.",
            ["cloud.expired"]          = "The Google Drive connection expired - connect again.",
            ["cloud.noTargetPath"]     = "The clip has no target path.",
            ["cloud.noRemoteId"]       = "The clip has no cloud identifier.",
            ["config.transcribeBusy"]  = "The folder cannot be changed while transcription is running.",
            ["config.pathRequired"]    = "A folder path is required.",
            ["config.pathMissing"]     = "Folder does not exist: {0}",
            ["config.notAFolder"]      = "This is not a folder: {0}",
            ["config.badTheme"]        = "Unsupported colour theme.",
            ["config.badLanguage"]     = "Unsupported language.",
            ["folder.nameTooLong"]     = "Folder name is too long (100 characters maximum).",
            ["folder.duplicate"]       = "A folder named “{0}” already exists.",
            ["media.pathMissing"]      = "The path does not exist.",
            ["media.explorerFailed"]   = "Could not open File Explorer: {0}",
            ["segment.textEmpty"]      = "The text cannot be empty.",
            ["update.inProgress"]      = "An update is already in progress.",
            ["replay.badDuration"]     = "Replay length must be between 15 and 600 seconds.",
            ["replay.badFps"]          = "Supported FPS values: 30, 60 or 90.",
            ["replay.badQuality"]      = "Unsupported recording quality.",
            ["replay.badHotkey"]       = "Invalid shortcut - use a modifier and a key, for example Alt+F10.",
            ["replay.notRunning"]      = "The replay buffer is not running.",
            ["replay.saveInProgress"]  = "The previous replay is still being saved.",
            ["replay.bufferEmpty"]     = "The replay buffer is still empty - give it a few seconds.",
            ["replay.muxFailed"]       = "Could not assemble the replay (ffmpeg: {0})",
            ["replay.ffmpegStart"]     = "ffmpeg failed to start.",
            ["replay.savingTitle"]     = "Saving the replay…",
            ["replay.savingSubtitle"]  = "processing, one moment…",
            ["replay.savedTitle"]      = "Replay saved",
            ["replay.saveFailedTitle"] = "Could not save the replay",
            ["tray.open"]              = "Open KeepClip",
            ["tray.exit"]              = "Quit and stop recording",
            ["tray.tooltip"]           = "KeepClip - recording in the background",
            ["credential.tooLong"]     = "The secret is too long for Windows Credential Manager.",
            ["drive.badPhotoUrl"]      = "Invalid Google profile picture address.",
            ["drive.photoTooLarge"]    = "The Google profile picture is too large.",
            ["drive.badPhoto"]         = "Google did not return a valid profile picture.",
            ["drive.badPhotoSize"]     = "Invalid Google profile picture size.",
            ["drive.noUploadUrl"]      = "Google Drive did not return an upload session address.",
            ["drive.noRefreshToken"]   = "Google did not return a refresh token.",
            ["transcribe.decodeFailed"] = "Could not decode audio: {0}",
            ["transcribe.noModel"]     = "No transcription model could be started.",
            ["trash.moveFailed"]       = "Could not move to the Recycle Bin (code {0}).",
        },
        ["ru"] = new()
        {
            ["clip.notFound"]          = "Клип не существует.",
            ["clip.fileMissing"]       = "Файла больше нет на диске.",
            ["clip.playbackNotReady"]  = "Предпросмотр клипа ещё не готов.",
            ["folder.nameRequired"]    = "Требуется имя папки.",
            ["folder.notFound"]        = "Папка не существует.",
            ["segment.notFound"]       = "Сегмент не существует.",
            ["search.queryRequired"]   = "Введите слова для поиска.",
            ["cloud.missingClientFile"] = "В папке data отсутствует файл google_client.json.",
            ["cloud.missingClientId"]  = "В google_client.json отсутствует client_id.",
            ["update.noInstaller"]     = "В последнем выпуске нет файла установщика.",
            ["replay.ffmpegMissing"]   = "В tools\bin нет ffmpeg.exe — запустите setup.ps1.",
            ["audio.noEndpoint"]       = "Не найдено аудиоустройство для записи.",
            ["cloud.notConnected"]     = "Нет подключения к Google Диску.",
            ["cloud.expired"]          = "Подключение к Google Диску истекло — подключитесь заново.",
            ["cloud.noTargetPath"]     = "У клипа нет целевого пути.",
            ["cloud.noRemoteId"]       = "У клипа нет идентификатора в облаке.",
            ["config.transcribeBusy"]  = "Нельзя менять папку во время транскрипции.",
            ["config.pathRequired"]    = "Требуется путь к папке.",
            ["config.pathMissing"]     = "Папка не существует: {0}",
            ["config.notAFolder"]      = "Это не папка: {0}",
            ["config.badTheme"]        = "Неподдерживаемая цветовая тема.",
            ["config.badLanguage"]     = "Неподдерживаемый язык.",
            ["folder.nameTooLong"]     = "Имя папки слишком длинное (максимум 100 символов).",
            ["folder.duplicate"]       = "Папка с именем «{0}» уже существует.",
            ["media.pathMissing"]      = "Путь не существует.",
            ["media.explorerFailed"]   = "Не удалось открыть Проводник: {0}",
            ["segment.textEmpty"]      = "Текст не может быть пустым.",
            ["update.inProgress"]      = "Обновление уже выполняется.",
            ["replay.badDuration"]     = "Длительность повтора должна быть в диапазоне 15–600 секунд.",
            ["replay.badFps"]          = "Поддерживаемые значения FPS: 30, 60 или 90.",
            ["replay.badQuality"]      = "Неподдерживаемое качество записи.",
            ["replay.badHotkey"]       = "Неверное сочетание — используйте модификатор и клавишу, например Alt+F10.",
            ["replay.notRunning"]      = "Буфер повтора не запущен.",
            ["replay.saveInProgress"]  = "Предыдущий повтор ещё сохраняется.",
            ["replay.bufferEmpty"]     = "Буфер повтора ещё пуст — подождите несколько секунд.",
            ["replay.muxFailed"]       = "Не удалось собрать повтор (ffmpeg: {0})",
            ["replay.ffmpegStart"]     = "Не удалось запустить ffmpeg.",
            ["replay.savingTitle"]     = "Сохранение повтора…",
            ["replay.savingSubtitle"]  = "обработка, минуту…",
            ["replay.savedTitle"]      = "Повтор сохранён",
            ["replay.saveFailedTitle"] = "Не удалось сохранить повтор",
            ["tray.open"]              = "Открыть KeepClip",
            ["tray.exit"]              = "Выйти и остановить запись",
            ["tray.tooltip"]           = "KeepClip — запись в фоне",
            ["credential.tooLong"]     = "Секрет слишком длинный для Диспетчера учётных данных.",
            ["drive.badPhotoUrl"]      = "Неверный адрес фото профиля Google.",
            ["drive.photoTooLarge"]    = "Фото профиля Google слишком большое.",
            ["drive.badPhoto"]         = "Google не вернул корректное фото профиля.",
            ["drive.badPhotoSize"]     = "Неверный размер фото профиля Google.",
            ["drive.noUploadUrl"]      = "Google Диск не вернул адрес сессии загрузки.",
            ["drive.noRefreshToken"]   = "Google не вернул токен обновления.",
            ["transcribe.decodeFailed"] = "Не удалось декодировать аудио: {0}",
            ["transcribe.noModel"]     = "Не удалось запустить ни одну модель транскрипции.",
            ["trash.moveFailed"]       = "Не удалось переместить в Корзину (код {0}).",
        },
        ["uk"] = new()
        {
            ["clip.notFound"]          = "Кліп не існує.",
            ["clip.fileMissing"]       = "Файла більше немає на диску.",
            ["clip.playbackNotReady"]  = "Попередній перегляд кліпу ще не готовий.",
            ["folder.nameRequired"]    = "Потрібна назва теки.",
            ["folder.notFound"]        = "Тека не існує.",
            ["segment.notFound"]       = "Сегмент не існує.",
            ["search.queryRequired"]   = "Введіть слова для пошуку.",
            ["cloud.missingClientFile"] = "У теці data бракує файлу google_client.json.",
            ["cloud.missingClientId"]  = "У google_client.json бракує client_id.",
            ["update.noInstaller"]     = "Найновіший випуск не містить файлу інсталятора.",
            ["replay.ffmpegMissing"]   = "У tools\bin немає ffmpeg.exe — запустіть setup.ps1.",
            ["audio.noEndpoint"]       = "Не знайдено аудіопристрій для запису.",
            ["cloud.notConnected"]     = "Немає з’єднання з Google Диском.",
            ["cloud.expired"]          = "З’єднання з Google Диском завершилося — підключіться знову.",
            ["cloud.noTargetPath"]     = "Кліп не має цільового шляху.",
            ["cloud.noRemoteId"]       = "Кліп не має ідентифікатора у хмарі.",
            ["config.transcribeBusy"]  = "Не можна змінювати теку під час транскрипції.",
            ["config.pathRequired"]    = "Потрібен шлях до теки.",
            ["config.pathMissing"]     = "Тека не існує: {0}",
            ["config.notAFolder"]      = "Це не тека: {0}",
            ["config.badTheme"]        = "Непідтримувана колірна тема.",
            ["config.badLanguage"]     = "Непідтримувана мова.",
            ["folder.nameTooLong"]     = "Назва теки задовга (щонайбільше 100 символів).",
            ["folder.duplicate"]       = "Тека з назвою «{0}» уже існує.",
            ["media.pathMissing"]      = "Шлях не існує.",
            ["media.explorerFailed"]   = "Не вдалося відкрити Провідник: {0}",
            ["segment.textEmpty"]      = "Текст не може бути порожнім.",
            ["update.inProgress"]      = "Оновлення вже триває.",
            ["replay.badDuration"]     = "Тривалість повтору має бути в межах 15–600 секунд.",
            ["replay.badFps"]          = "Підтримувані значення FPS: 30, 60 або 90.",
            ["replay.badQuality"]      = "Непідтримувана якість запису.",
            ["replay.badHotkey"]       = "Неправильне поєднання — використайте модифікатор і клавішу, наприклад Alt+F10.",
            ["replay.notRunning"]      = "Буфер повтору не запущено.",
            ["replay.saveInProgress"]  = "Попередній повтор ще зберігається.",
            ["replay.bufferEmpty"]     = "Буфер повтору ще порожній — зачекайте кілька секунд.",
            ["replay.muxFailed"]       = "Не вдалося зібрати повтор (ffmpeg: {0})",
            ["replay.ffmpegStart"]     = "Не вдалося запустити ffmpeg.",
            ["replay.savingTitle"]     = "Збереження повтору…",
            ["replay.savingSubtitle"]  = "обробка, хвилинку…",
            ["replay.savedTitle"]      = "Повтор збережено",
            ["replay.saveFailedTitle"] = "Не вдалося зберегти повтор",
            ["tray.open"]              = "Відкрити KeepClip",
            ["tray.exit"]              = "Вийти та зупинити запис",
            ["tray.tooltip"]           = "KeepClip — запис у фоні",
            ["credential.tooLong"]     = "Секрет задовгий для Диспетчера облікових даних.",
            ["drive.badPhotoUrl"]      = "Неправильна адреса фото профілю Google.",
            ["drive.photoTooLarge"]    = "Фото профілю Google завелике.",
            ["drive.badPhoto"]         = "Google не повернув коректне фото профілю.",
            ["drive.badPhotoSize"]     = "Неправильний розмір фото профілю Google.",
            ["drive.noUploadUrl"]      = "Google Диск не повернув адресу сесії завантаження.",
            ["drive.noRefreshToken"]   = "Google не повернув токен оновлення.",
            ["transcribe.decodeFailed"] = "Не вдалося декодувати аудіо: {0}",
            ["transcribe.noModel"]     = "Не вдалося запустити жодну модель транскрипції.",
            ["trash.moveFailed"]       = "Не вдалося перемістити до Кошика (код {0}).",
        },
    };
}
